name: "\U0001F4A1 기능 개선"
description: 기존 기능을 개선하거나 사용자 경험을 향상시키는 이슈를 제안할 때 사용합니다.
title: "[Enhancement] "
labels: ["enhancement", "feature"]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: 현재 동작
      description: 현재 기능이 어떻게 동작하는지 설명해주세요.
  - type: textarea
    id: improvement
    attributes:
      label: 개선 방향
      description: 어떤 점을 어떻게 개선하고 싶은지 설명해주세요.
  - type: textarea
    id: expected-benefit
    attributes:
      label: 기대 효과
      description: 이 개선이 어떤 문제를 해결하거나 어떤 가치를 줄 수 있을까요?
