name: 배포 준비
description: 버전 배포 및 마켓 등록을 위한 준비 사항 정리
title: "[Release] "
labels: ["release"]
body:
  - type: input
    attributes:
      label: 배포 버전
      placeholder: 예) v1.0.0

  - type: checkboxes
    attributes:
      label: 체크리스트
      options:
        - label: 코드 병합 완료
        - label: 테스트 완료
        - label: 버전 정보 갱신
        - label: 앱 아이콘 / 스크린샷 확인
        - label: 마켓용 설명 작성
        - label: 마켓 업로드 완료

  - type: textarea
    attributes:
      label: 릴리즈 노트 개요
      placeholder: 주요 변경 사항 요약
