name: ⚙️ 인프라 개선 요청
description: CI/CD, 모니터링, 보안, 품질 도구, 자동화 스크립트 등 인프라 관련 요청사항을 등록해주세요.
title: "[Infra] "
labels: ["infra"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ 인프라 작업 제안서

        다음과 같은 작업을 등록할 수 있어요:
        - CI/CD 개선 (예: GitHub Actions, Jenkins, GitLab CI)
        - 품질 도구 도입 (예: SonarQube, ESLint, Detekt)
        - 보안/테스트 자동화 (예: SAST, DAST, 테스트 커버리지 리포트)
        - 시스템 환경 개선 (예: 빌드 속도, 캐시 전략, 의존성 정리)
        - 클라우드 설정/모니터링 (예: AWS/GCP, 로그 수집, 알림 설정)

  - type: textarea
    id: purpose
    attributes:
      label: 🎯 작업 목적 및 기대 효과
      description: 인프라 개선을 통해 해결하고 싶은 문제, 기대되는 효과를 작성해주세요.
      placeholder: |
        예시:
        - 코드 품질을 자동으로 관리하고 싶어요.
        - 테스트 실패 시 Slack으로 알림을 받고 싶어요.
        - 릴리즈 프로세스를 간소화하고 싶어요.
      value: ""
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 📌 적용 범위
      description: 특정 프로젝트, 레포지토리, 또는 공통 설정 등 적용 대상 범위를 작성해주세요.
      placeholder: |
        예시:
        - Android 프로젝트 전체
        - backend-monorepo
        - 모든 PR에 적용
      value: ""
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: ❗ 현재 불편한 점
      description: 반복 작업이나 개선이 필요한 인프라 상황을 적어주세요.
      placeholder: |
        예시:
        - 테스트가 실패해도 아무도 모름
        - 코드 커버리지 확인이 번거로움
        - 배포 과정이 수동임
      value: ""
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🧭 작업 우선순위
      description: 얼마나 시급한가요?
      options:
        - 🟢 낮음 (편하면 좋음)
        - 🟡 중간 (불편하지만 참을만 함)
        - 🔴 높음 (자주 반복되고 급함)
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 📎 관련 참고사항 또는 문서
      description: 참고할 수 있는 스크립트, 링크, 예시, 로그 등 있으면 추가해주세요.
      placeholder: |
        예시:
        - 참고 스크립트: `.github/workflows/test.yml`
        - 비슷한 구현 사례: https://github.com/org/repo/issues/123
        - Slack 알림 포맷 예시 첨부 등
      value: ""
    validations:
      required: false
